name       : kconfigwidgets
version    : 5.69.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/kconfigwidgets-5.69.0.tar.xz : 6fcf93cf2a5c7f81a272f685d329e711a21d2ff314fe7737a52592a138c37473
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Widgets for configuration dialogs
description: |
    Widgets for configuration dialogs
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kauth-devel
        - kcodecs-devel
        - kconfig-devel
        - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
