name       : kconfigwidgets
version    : 5.45.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/kconfigwidgets-5.45.0.tar.xz : 349ccd412fbe7130026e389edc6d1186ec0a1610dfdd43fd9ff00867ba50404e
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Widgets for configuration dialogs
description: |
    Widgets for configuration dialogs
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kauth-devel
        - kcodecs-devel
        - kconfig-devel
        - kwidgetsaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
