name       : kconfigwidgets
version    : 5.53.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kconfigwidgets-5.53.0.tar.xz : 7b0a87f74462adf9738a41599c63f8fb044a5f955420c74a71274ee582a4fe2e
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Widgets for configuration dialogs
description: |
    Widgets for configuration dialogs
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kauth-devel
        - kcodecs-devel
        - kconfig-devel
        - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
