name       : kconfigwidgets
version    : 5.32.0
release    : 4
source     :
    - http://download.kde.org/stable/frameworks/5.32/kconfigwidgets-5.32.0.tar.xz : 837f020c1b15f0d3bc9be5923983ed00f6d6b298186b8d127089ee6be65000b3
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Widgets for configuration dialogs
description: |
    Widgets for configuration dialogs
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kguiaddons-devel
    - ki18n-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kauth-devel
        - kcodecs-devel
        - kconfig-devel
        - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
