name       : kconfigwidgets
version    : 5.90.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.90/kconfigwidgets-5.90.0.tar.xz : 98ff947d80bd3c55bc0758b0fc9e1300078f1a9ad8a8983e737d6cd189e9a1ea
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - MIT
component  : desktop.library
summary    : Widgets for configuration dialogs
description: |
    Widgets for configuration dialogs
optimize   : lto
builddeps  :
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kauth-devel
        - kcodecs-devel
        - kconfig-devel
        - kcoreaddons-devel
        - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
