name       : kconfigwidgets
version    : 5.96.0
release    : 64
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/kconfigwidgets-5.96.0.tar.xz : 1482f42562be8db93c9161acf2b24fa839f05bc893f22f02a3c1e972e733b210
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - MIT
component  : desktop.library
summary    : Widgets for configuration dialogs
description: |
    Widgets for configuration dialogs
optimize   : lto
builddeps  :
    - kauth-devel
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kauth-devel
        - kcodecs-devel
        - kconfig-devel
        - kcoreaddons-devel
        - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
